### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
After sending in inertiajs/inertia-react#15 and inertiajs/inertia#22, I tried to figure out the Typescript typings for the `inertia-vue` package.

Here too @sebastiandedeyne is the best man to review I think

### CODE REVIEW

**Comment by belzaaron** [comment]
This would be great! Maybe we could add a page to the repo's wiki documenting the install/setup process. As ts loader and some other dependencies would be required to get everything all working. I'll gladly contribute! Awesome work @MichaelDeBoey !

**Comment by MichaelDeBoey** [comment]
Thanks for your kind words @belzaaron. 🙂

I think that sort of things would maybe fit better in the official website on the page of the adapter

**Comment by belzaaron** [comment]
> Thanks for your kind words @belzaaron. 🙂
> 
> I think that sort of things would maybe fit better in the official website on the page of the adapter

That would be perfect. I have not seen the docs up yet, if they are could you point me toward them? If they're not up, no worries; I'll be around, I love this concept so much! Great work by all contributors !

**Comment by MichaelDeBoey** [comment]
@belzaaron The inertiajs/inertiajs.com is online, but @reinink hasn't pushed anything yet, so hold your horses boy 😉

**Comment by MichaelDeBoey** [comment]
@sebastiandedeyne Types should be up to date now

**Comment by chiefluke** [comment]
When will this PR be merged? I've been waiting for it for a month now. It will make Inertia a lot more accessible for typescript users

**Comment by sebastiandedeyne** [comment]
I have zero experience with Vue together with TypeScript, so someone else would need to try this out first before I merge. Anyone up for helping out?

**Comment by MichaelDeBoey** [comment]
@sebastiandedeyne I've updated the typings to the modern way we use in core and  the react adapter

**Comment by reinink** [comment]
Going to merge this in, even though I have not tested it at all. @MichaelDeBoey, you'll have to keep this updated moving forward...because I can't.

**Comment by MichaelDeBoey** [comment]
@reinink No problem at all! 🙂

**Comment by reinink** [comment]
Thanks man, I really appreciate all your help on this project!

**Pull request merged**
