### PR TITLE
Remove Laravel Mix configuration code

### PR DESCRIPTION
**Pull request by imacrayon**
Dynamic imports work out of the box with the latest Laravel Mix: https://github.com/JeffreyWay/laravel-mix/commit/55371b58df64abac60991d1d15f2b435a9585c60

### CODE REVIEW

**Comment by reinink** [comment]
Do you know which version (of Mix) this was added?

**Comment by imacrayon** [comment]
I was able to compile PingCRM with the config line remove and version 4.0.3 and up...that seems kind of weird though. Maybe somebody else could verify?

**Comment by nwentling5** [comment]
@imacrayon I can verify. 

Before running `npm install` I did the following:

- Changed Laravel Mix version from `"^4.0.7"` to `"4.0.3"`.
- Removed the following babel lines:
  * https://github.com/inertiajs/pingcrm/blob/master/package.json#L13
  * https://github.com/inertiajs/pingcrm/blob/master/webpack.mix.js#L33-L35 

Didn't have any issues compiling assets and the demo is working fine.

**Comment by adriandmitroca** [comment]
This is not entirely right. It's true that by default, Laravel Mix works with dynamic support (in theory). The issue is with Webpack 4 behind the scenes though. Imports simply fail if you have styles inside your dynamic imports and production builds will be simply broken.

I can tell you that there is a quick workaround for the issue by importing blank scss file at the top of your app.js file, but still - dynamic imports are fully supported working when you're using Mix.

Jeffrey Way mentioned once that this issue can be fixed only after migrating Mix to Webpack 5.

**Comment by iKlsR** [comment]
Latest mix doesn't fix the issue for me oddly. I can't consistently run `dev` or `prod`, I still have to `watch`, delete some code, add it back and wait on that build else I get the same `TypeError: modules[moduleId] is undefined` which leads back to roughly https://github.com/JeffreyWay/laravel-mix/issues/2064 and https://github.com/JeffreyWay/laravel-mix/issues/2074.

@nwentling5's suggestion doesn't work either.

**Comment by reinink** [comment]
Closing this PR since we're no longer maintaining the docs in the readme. Thanks for the contribution either way! 👍

**Pull request closed without merging**
