### PR TITLE
Add AppMethods type

### LINKED ISSUE #89: Incorrect typings
I'm using `@inertiajs/inertia 0.1.4` and `@inertiajs/inertia-vue 0.1.2`. 
I'm refactoring my app using TypeScript, but I got this error as soon as I enabled TypeScript linting in my main file: 

<details>
  <summary>Error message</summary>

```
No overload matches this call.
  Overload 1 of 2, '(plugin: PluginObject<unknown> | PluginFunction<unknown>, options?: unknown): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, never, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<unknown> | PluginFunction<unknown>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<unknown> | PluginFunction<unknown>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<unknown>'.
  Overload 2 of 2, '(plugin: PluginObject<any> | PluginFunction<any>, ...options: any[]): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, never, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<any> | PluginFunction<any>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<any>'.
```
</details>

I believe the typings may be incorrect?

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Probably fixes #89

@hawezo If you can provide a reproduction, I can test it out if you want.

@sebastiandedeyne Or maybe you have something to let me check it out? 🤔

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
Why does `created` need to be types?

**Comment by MichaelDeBoey** [comment]
@sebastiandedeyne No need for it, but just wanted to make the `AppMethods` be complete 🙂

**Comment by hawezo** [comment]
Thanks! Unfortunately, it doesn't look like it fixes it. 




>  If you can provide a reproduction, I can test it out if you want.

I created a repository, but it really is nothing. Just have Inertia and Vue, try to initialize inertia, and the TypeScript linting will tell you that.

```typescript
import Vue from 'vue';
import { InertiaApp } from '@inertiajs/inertia-vue';

Vue.use(InertiaApp); // <-- error here
```
https://github.com/hawezo/inertia-ts-types

<details>
<summary>Error</summary>

```
No overload matches this call.
  Overload 1 of 2, '(plugin: PluginObject<unknown> | PluginFunction<unknown>, options?: unknown): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, AppMethods, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<unknown> | PluginFunction<unknown>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<unknown> | PluginFunction<unknown>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<unknown>'.
  Overload 2 of 2, '(plugin: PluginObject<any> | PluginFunction<any>, ...options: any[]): VueConstructor<Vue>', gave the following error.
    Argument of type 'Component<AppData<PageProps>, AppMethods, never, AppProps<PagePropsBeforeTransform, PageProps>>' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.
      Type 'VueConstructor<Vue>' is not assignable to type 'PluginObject<any> | PluginFunction<any>'.
        Property 'install' is missing in type 'VueConstructor<Vue>' but required in type 'PluginObject<any>'.
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "inertia-ts-types",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@inertiajs/inertia": "^0.1.6",
    "@inertiajs/inertia-vue": "MichaelDeBoey/inertia-vue#appmethods-typings",
    "vue": "^2.6.10"
  }
}
```
</details>

**Comment by MichaelDeBoey** [comment]
@hawezo I'll take a look at it later today 🙂

**Comment by MichaelDeBoey** [comment]
Looking a bit closer into the types (and at [`vue-router`'s types](https://github.com/vuejs/vue-router/tree/dev/types)), I think the problem is we're using the same thing as a plugin _**and**_ as a component:

As a **plugin**:
```ts
Vue.use(InertiaApp)
```

As a **component**:
```ts
new Vue({
  render: h => h(InertiaApp, {
    props: {
      // ...
    },
  }),
}).$mount(app);
```

The [main export of `vue-router`](https://github.com/vuejs/vue-router/blob/902fbd94b91154388fbc8ab1b4f507f378042fab/src/index.js) isn't a component, since it doesn't render anything.
Our `InertiaApp` _is_ a component (it renders the child), so I think the typing is correct.

I think we should create a new `InertiaPlugin` instead, which would only contain the logic for the install method.

CC @reinink @sebastiandedeyne

**Comment by reinink** [comment]
> I think we should create a new `InertiaPlugin` instead, which would only contain the logic for the install method.

Yup, agreed. Sebastian actually just talked about this yesterday. Can you make that happen?

**Comment by MichaelDeBoey** [comment]
@reinink Do you want me to create a new PR for this or just add it to this one? 🤔

**Comment by reinink** [comment]
Maybe create a new one?

**Comment by reinink** [comment]
Hello, thanks so much for your interest in Inertia.js and for contributing back to it. However, in an effort to make the project easier to maintain, we've merged the four client-side libraries (`inertia`, `inertia-react`, `inertia-svelte` and `inertia-vue`) into a single [monorepo](https://github.com/inertiajs/inertia). If you feel this PR is still relevant, please resubmit it there. Sorry for the inconvenience. ❤️

**Pull request closed without merging**
