### PR TITLE
Add support for persistent nested layouts

### PR DESCRIPTION
**Pull request by reinink**
This PR adds support for optional persistent (nested) layouts.

## Demo

Note in this demo how the left navigation scroll position is persisted between page visits. Notice also how the value of the input in the nested layout is persists  between page visits.

Persistent Nested Layouts

> Sorry, I don't know why this GIF is playing so slow 🐢

## How it works

This is done using a new custom `layout` property in your page components.

```js
import Layout from './Layout'

export default {
  layout: (h, page) => h(Layout, [page]),
  // ...
}
```

Or the short form:

```js
import Layout from './Layout'

export default {
  layout: Layout,
  // ...
}
```

And with a nested layout:

```js
import SiteLayout from './SiteLayout'
import NestedLayout from './NestedLayout'

export default {
  layout: (h, page) => {
    return h(SiteLayout, [
      h(NestedLayout, [page]),
    ])
  },
  // ...
}
```

Each layout file must contain a `<slot />`.

## Page/layout communication

You can pass props to the layout:

```js
import Layout from './Layout'

export default {
  layout: (h, page) => h(Layout, { props: { title: 'Page title' } }, [page]),
  // ...
}
```

However, it's not possible (at least from what I can tell) to pass reactive props to a layout from a page component. Instead, you can use the `$parent` property to achieve this. For example, if you wanted to dynamically update the page title in your layout component:

```js
watch: {
  name: {
    immediate: true,
    handler(name) {
      this.$parent.updateTitle(name)
    },
  },
},
```

It might be better to just use a global event bus to handle page/layout communication.

## New custom property

This update introduces a second custom property (`layout`) in addition to one we already have (`remember`). Makes me wonder if there would be wisdom to putting it all under an `inertia` property.

```js
import Layout from './Layout'

export default {
  inertia: {
    remember: 'form',
    layout: Layout,
  },
  // ...
}
```

## Scroll management

This is also going to require some work around scroll management. Currently Inertia resets the scroll position on the window (`window..scrollTo(0, 0)`), however this won't work if you have nested scroll containers. I think the easiest way to handle this is with a scroll region marker:

```html
<div class="overflow-y-auto" scroll-region>
  <slot />
</div>
```

Inertia would then be updated like this:

```js
setScroll(preserveScroll) {
  if (!preserveScroll) {
    document.querySelectorAll('body,[scroll-region]')
      .forEach(region => region.scrollTo(0, 0))
  }
},
```

### CODE REVIEW

**Comment by reinink** [comment]
Another option is to not use a named exports, and instead use a property:

```js
import Layout from '@/Shared/Layout'

export default {
  layout(h, child) {
    return h(Layout, {
      props: { title: 'Dashboard' },
    }, [child])
  },
}
```

**Comment by klaasgeldof** [comment]
So cool! Thanks a lot for this. 

But how does the active state in the left navigation change if that component is persisted? With a watcher in the nav component?

**Comment by reinink** [comment]
>But how does the active state in the left navigation change if that component is persisted? With a watcher in the nav component?

@klaasgeldof Great question! So, it's important to realize that the layout component is still being re-rendered, so active states and any other dynamic layout content will still update. However, because the layout is no longer rendered within the page component, Vue doesn't throw it away on page changes, but instead patches the existing instance of it. Meaning any local state, such as scrolling, or even data will be preserved.

In the case of my PingCRM example above, I made NO changes to the [MainMenu](https://github.com/inertiajs/pingcrm/blob/master/resources/js/Shared/MainMenu.vue) component, and it just worked. 👍

**Comment by klaasgeldof** [comment]
Awesome 😃

**Comment by inxilpro** [comment]
FWIW, this is how we're dealing with this in React right now:

```jsx
import React from 'react';
import { InertiaApp } from '@inertiajs/inertia-react';
import Layout from './Layout.js';

export default function App({ initialPage }) {
  const renderComponent = ({ Component, key, props }) => {
    return (
      <Layout>
        <Component key={ key } { ...props } />
      </Layout>
    );
  };

  return (
    <InertiaApp
      initialPage={ initialPage }
      resolveComponent={ /* ... */ }
      children={ renderComponent }
    />
  );
}
```

I just played around with it, and this seems to work just fine:

```jsx
const renderComponent = ({ Component, key, props }) => {
  const LayoutComponent = Component.layout || React.Fragment;
  return (
    <LayoutComponent>
      <Component key={ key } { ...props } />
    </LayoutComponent>
  );
};
```

Then the page just looks like:

```jsx
import Layout from './Layout.js';

export default function SamplePage(props) {
  /* Render sample page */
}

SamplePage.layout = Layout;
```

**Comment by reinink** [comment]
@inxilpro Yes, not bad! The issue with your first option is that you always have to use the same layout. Your second solution is better, but still doesn't support nesting layouts. The trick with the approach I'm proposing is that Inertia passes the child (the page component) back so you can nest it within one (or many) layouts. 👌

**Comment by inxilpro** [comment]
Yeah, I wasn’t super happy with our current solution because it basically means that we need different builds for each parent layout. 

The second solution *should* work with nested layouts, although I’m not familiar with Vue so I could be translating things in my head wrong, because your parent layout will just take the `page` as a prop, and can pass it down as deep as it needs to…

**Comment by danielstgt** [comment]
This is exactly what I needed, thank you @reinink! 🙂

One question though:

Is it somehow possible to tell a parent component that it is or should be nested without specifying it in the page itself?

### Example of the current state:

`WrapperLayout.vue` a component that is the most outer component:

```html
<template>
    <div>
        <p>wrapper, stays mounted</p>

        <slot></slot>
    </div>
</template>
```

`DefaultLayout.vue` a **global** Vue component for the most common pages:

```html
<template>
    <div>
        <p>default page layout</p>

        <slot></slot>
    </div>
</template>
```

`ExamplePage.vue` that uses the default layout component from above:

```html
<template>
    <default-layout>
        <h1>Example</h1>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    </default-layout>
</template>

<script>
import WrapperLayout from '@/Layouts/WrapperLayout';

export default {
    layout: (h, page) => h(WrapperLayout, [page]),
}
</script>
```

This works fine so far, but I'm repeating the instruction that the `DefaultLayout.vue` uses the `WrapperLayout.vue` inside each page.

### Example with what I'm trying to accomplish (not working):

`DefaultLayout.vue` with the info that it is wrapped:

```html
<template>
    <div>
        <p>default layout</p>

        <slot></slot>
    </div>
</template>

<script>
import WrapperLayout from '@/Layouts/WrapperLayout';

export default {
    layout: (h, page) => h(WrapperLayout, [page]),
}
</script>
```

And now `ExamplePage.vue` would only need to know that it uses the `DefaultLayout.vue`:

```html
<template>
    <default-layout>
        <h1>Example</h1>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    </default-layout>
</template>
```
The most outer wrapper layout is being ignored, which is totally expected because `DefaultLayout.vue` doesn't get called from Inertia, practically not responsible for passing the page. However, is there any solution how it could work? Sorry if this is actually not really related to Inertia and more Vue or JS related.

This is not a showstopper at all at the end of the day, the new solution with nested layouts opens up so many new possibilities and I love it! 🎉

**Comment by mpskovvang** [comment]
Much appreciated, thanks!

However, can this feature somehow be used in conjunction with scoped slots?

Imagine this layout:
```vue
<template>
    <div>
        <slot name="header" />
        <slot />
    </div>
</template>
```

The `layout` property only injects the page component into the `default` slot, but from the same page component, it would be useful to also inject the `header` content.

Can this be achieved? Perhaps a workaround? I'm new to the Vue framework, but I found there exists a `slot` prop: https://stackoverflow.com/questions/50150668/how-to-create-vue-js-slot-programatically

**Pull request merged**
