### PR TITLE
Add tag prop to inertia-link

### PR DESCRIPTION
**Pull request by RSpeekenbrink**
Add the vue router Tag prop like mentioned in #71. But since it's more than 30 days ago the author of that PR last answered, and this is something people (at least I) are really in need for, I decided to split the 2 features of #71 and push this one myself so at least the tag prop could be merged.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@reinink Is there anything preventing pulling this in?

**Comment by Juhlinus** [comment]
@m1guelpf Lack of time, most likely. 

I'm curious as to if @digistorm actually abandoned the PR, or if the lack of replies afterwards led them to not update any further. If @digistorm is willing to continue updating their PR, then this one(#82) should be closed in favor of that one(#71).

Thanks for your contribution, @RSpeekenbrink, let's put this on ice until we have this sorted out. :smile:

**Comment by RSpeekenbrink** [comment]
@Juhlinus Agreed 😄

**Comment by RSpeekenbrink** [comment]
@Juhlinus still no response in a week. How long do you want to wait? Would like to use the original repo again instead of the fork :)

**Comment by Juhlinus** [comment]
Ping @reinink 

I guess we can close #71 in favor of this.

**Comment by reinink** [comment]
Yeah honestly I don't mind merging this in and then waiting on the other PR.

What's the primary use-case for this feature? Creating buttons?

**Comment by reinink** [comment]
Just doing more digging into this, I wonder if this is actually the right approach. They are actually removing this option from Vue Router (see [here](https://github.com/vuejs/rfcs/pull/34)). I wonder if we'd be wise going with a similar approach. I believe this is also what Next.js does.

**Comment by RSpeekenbrink** [comment]
> Just doing more digging into this, I wonder if this is actually the right approach. They are actually removing this option from Vue Router (see [here](https://github.com/vuejs/rfcs/pull/34)). I wonder if we'd be wise going with a similar approach. I believe this is also what Next.js does.

Sound better indeed. I'll look into this aswell.

**Comment by RSpeekenbrink** [comment]
> Just doing more digging into this, I wonder if this is actually the right approach. They are actually removing this option from Vue Router (see [here](https://github.com/vuejs/rfcs/pull/34)). I wonder if we'd be wise going with a similar approach. I believe this is also what Next.js does.

Sounds better indeed. I've created a PR based on that RFC (#96).

**Comment by reinink** [comment]
Hello, thanks so much for your interest in Inertia.js and for contributing back to it. However, in an effort to make the project easier to maintain, we've merged the four client-side libraries (`inertia`, `inertia-react`, `inertia-svelte` and `inertia-vue`) into a single [monorepo](https://github.com/inertiajs/inertia). If you feel this PR is still relevant, please resubmit it there. Sorry for the inconvenience. ❤️

**Pull request closed without merging**
