### PR TITLE
Add Transform Middleware to readme

### PR DESCRIPTION
**Pull request by thoresuenert**
Document this hidden feature ;)

My way to write docs is by far not the best.
Handle this more as an reminder.

**Edit**
Here is the orginal Text from @reinink 
https://github.com/inertiajs/inertia-vue/pull/27

### CODE REVIEW

**Comment by njoguamos** [comment]
I hope this get merged soon.

**Comment by reinink** [comment]
Thanks for this @thoresuenert!

**Comment by njoguamos** [comment]
Should it be worth noting that  `Errors` object need to be imported? e.g

```javascript 
import {Errors} from "./utils/Errors"; //
```

Just to be clear

**Comment by reinink** [comment]
I considered it, but that's honestly an implementation detail that could be different. For example, it may not even be imported...it could be a global class (for whatever reason).

**Comment by njoguamos** [comment]
Yeah I see the point now

**Pull request merged**
