### PR TITLE
Update docs with new version of Laravel Mix

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Just like https://github.com/inertiajs/inertia-react/pull/41

### CODE REVIEW

**Comment by reinink** [comment]
Has dynamic imports with styles been fixed in Laravel Mix v4? If not, we should probably leave that limitation warning.

**Comment by MichaelDeBoey** [comment]
@reinink It's been removed in the `react` adapter too.

**Comment by reinink** [comment]
I understand...but it's not an issue with React...it's an issue with styles in single-file vue components, in Mix v4 from what I understand.

**Comment by MichaelDeBoey** [comment]
@reinink Reverted that part 🙂

**Comment by reinink** [comment]
Perfect, thanks!

**Comment by MichaelDeBoey** [comment]
With pleasure! 🙂

**Pull request merged**
