### PR TITLE
InertiaLink scoped slot

### PR DESCRIPTION
**Pull request by RSpeekenbrink**
This change will implement the scoped slot feature just like the Vue-Router RFC: https://github.com/vuejs/rfcs/pull/34 .

The idea of this RFC is to provide a scoped slot that allow app developers to easily extend Links based on their applications and custom components/layouts and to allow library authors to provide an even easier integration.

It will replace the need for a tag prop. Instead you can replace the default anchor tag with a custom scope like this for example:

```vue
/* In your Vue template: */
<inertia-link href="/about" v-slot="{ href, navigate }">
  <button :href="href" @click="navigate">
    About us
  </button>
</inertia-link>

/* output: */
<button href="/about">
  About us
</button>
```

While it still allows to use the InertiaLink component just like before:

```vue
/* In your Vue template: */
<inertia-link href="/about" >
  <h1>About us</h1>
</inertia-link>

/* output: */
<a href="/about">
  <h1>About us</h1>
</a>
```

In order to be able to use the scopedSlots state the functional state had to be removed from the InertiaLink component.

### CODE REVIEW

**Comment by reinink** [comment]
Wow @RSpeekenbrink! That was fast. Give me a couple days to review this new PR. I'm a little behind. I really appreciate you putting this together. 👍

**Comment by RSpeekenbrink** [comment]
@reinink Any status update on this? 😃

**Comment by reinink** [comment]
Hey @RSpeekenbrink! Sorry, I've been slammed with work, and haven't had as much time for Inertia.js as I've wanted to lately. I hope to get to this soon, but it's really depending on my "free time". I've seriously been considering trying some type of fundraising/sponsorship to generate some cashflow to give me some runway with Inertia.

**Comment by Landish** [comment]
Before this PR is merged, if anyone needs solution for linking custom components/elements, this is what i came up with:

```html
<button @click.prevent="$inertia.visit('/destination-url')">Go to ...</button>
```

This should also work with [other methods](https://inertiajs.com/requests), such as `replace`, `post` and etc, but haven't tested though.  

Hope to see this feature soon!

**Comment by RSpeekenbrink** [comment]
Thanks @Landish, hope to see the feature soon too :)

**Comment by clmntgr** [comment]
Would be great to also have the `isActive` prop too, but not sure it's in the scope of this PR

**Comment by RSpeekenbrink** [comment]
@clmntgr https://github.com/inertiajs/inertia-vue/pull/71

**Comment by reinink** [comment]
Hello, thanks so much for your interest in Inertia.js and for contributing back to it. However, in an effort to make the project easier to maintain, we've merged the four client-side libraries (`inertia`, `inertia-react`, `inertia-svelte` and `inertia-vue`) into a single [monorepo](https://github.com/inertiajs/inertia). If you feel this PR is still relevant, please resubmit it there. Sorry for the inconvenience. ❤️

**Pull request closed without merging**
